name: "ew-deploy-dev"

on:
 push:
   branches:
    - main
   paths:
   - "terraform_dev/**"

 workflow_dispatch:

jobs:
  dev-plan:
   uses: K-Basavaraj/terraformworkspace/.github/workflows/rw-plan.yml@main
   with:
     path: terraform_dev
     tf_version: latest
     az_resource_group: labresgrp1
     az_storage_account: stgaccstate101
     az_container_name: devcontainer
     tf_key: dev
     tf_vars_file: dev.tfvars
   secrets:
     AZURE_AD_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
     AZURE_AD_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
     AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
     AZURE_AD_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}} 
  
  dev-apply:
     uses: K-Basavaraj/terraformworkspace/.github/workflows/rw-apply.yml@main
     needs: [dev-plan]
     with:
       path: terraform_dev
       tf_version: latest
       az_resource_group: labresgrp1
       az_storage_account: stgaccstate101
       az_container_name: devcontainer
       tf_key: dev
       tf_vars_file: dev.tfvars
     secrets:
       AZURE_AD_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
       AZURE_AD_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
       AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
       AZURE_AD_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
    