name: "ew-terraform-dev"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - "terraform_dev/**"

jobs:
  validate:
    uses: K-Basavaraj/terraformworkspace/.github/workflows/rw-oidc-validate.yml@feature-branch-27
    with:
      path: terraform_dev
      tf_version: latest
    secrets:
      AZURE_AD_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
      AZURE_AD_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
    


#   plan:
#     uses: K-Basavaraj/terraformworkspace/.github/workflows/rw-plan.yml@main
#     needs: [validate]
#     with:
#       path: terraform_dev
#       tf_version: latest
#       az_resource_group: labresgrp1
#       az_storage_account: stgaccstate101
#       az_container_name: devcontainer
#       tf_key: dev
#       tf_vars_file: dev.tfvars
#     secrets:
#       AZURE_AD_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
#       AZURE_AD_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
#       AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
#       AZURE_AD_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
