name: "ew-oidc_int_qa"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - "terraform_qa/**"

jobs:
  validate:
    uses: K-Basavaraj/terraformworkspace/.github/workflows/rw-validate.yml@main
    with:
      path: terraform_qa

  plan:
    uses: K-Basavaraj/terraformworkspace/.github/workflows/rw-plan.yml@main
    needs: [validate]
    with:
      path: terraform_dev
      tf_version: latest
      az_resource_group: labresgrp1
      az_storage_account: stgaccstate101
      az_container_name: devcontainer
      tf_key: qa
      tf_vars_file: qa.tfvars
      github_environment: qa
    secrets:
      AZURE_AD_CLIENT_ID: ${{ inputs.github_environment == 'dev' && secrets.AZURE_AD_CLIENT_ID || secrets.AZURE_AD_QA_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_AD_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
