name: "ew-terraform-dev"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - "terraform_dev/**"

jobs:
  validate:
    uses: K-Basavaraj/terraformworkspace/.github/workflows/rw-validate.yml@featurebranch3-adding-ewfile
    with:
      path: terraform_dev