name: "ew-terraform-dev"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - "terraform_dev/**"

jobs:
  validate:
    uses: K-Basavaraj/terraformworkspace/.github/workflows/rw-validate.yml@featurebranch3-adding-ewfile
    with:
      path: terraform_dev
      arm_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      arm_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      arm_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      arm_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
