name: "ew-terraform-dev"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - "terraform_dev**"

jobs:
  validate:
    uses: .github/workflows/rw-validate.yml@main
    with:
      path: terraform_dev
    secrets:
      arm_client_id: ${{secrets.AZURE_AD_CLIENT_ID}}
      arm_client_secret: ${{secrets.AZURE_AD_CLIENT_SECRET}}
      arm_subscription_id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      arm_tenant_id: ${{secrets.AZURE_AD_TENANT_ID}}
