name: OIDC Push

on:
  push:
    branches:
    - main

env:
  ROOT_PATH: "${{ github.workspace }}/src"
  environment: dev

permissions:
      id-token: write
      contents: read

jobs: 
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    # Log into Azure with OIDC integration
    - name: "Az CLI login"
      uses: azure/login@v1
      with:
        client-id: ${{secrets.AZURE_AD_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_AD_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

    # Run az commands to confirm sub access
    - name: 'Run az commands'
      run: |
        az account show

    # Run Terraform init
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}}
      env:
       ARM_USE_OIDC: true

    # Run a Terraform apply
    - name: Terraform apply
      id: apply
      working-directory: ${{env.ROOT_PATH}}
      env:
       ARM_USE_OIDC: true
      run: terraform apply -auto-approve