name: OIDC Pull Request

on:
  pull_request:
    branches:
      - main

env:
  ROOT_PATH: "${{ github.workspace }}/src"
  environment: dev

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: read

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Log into Azure with OIDC integration
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_AD_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_AD_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      # Run az commands to confirm sub access
      - name: "Run az commands"
        run: |
          az account show

      # Run Terraform init
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{env.ROOT_PATH}}
        env:
          ARM_USE_OIDC: true

      # Run a Terraform fmt
      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      # Run a Terraform validate
      - name: Terraform validate
        id: validate
        if: success() || failure()
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        run: terraform validate -no-color

      # Run a Terraform plan
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{env.ROOT_PATH}}
        env:
          ARM_USE_OIDC: true