name: "rw-oidc-terraform-validate"

on:
  workflow_call:
    inputs:
      path:
        description: 'Specify the path of the root Terraform module'
        required: true
        type: string
      tf_version:
        description: 'Specify the version of the terraform to use'
        required: true
        type: string

    secrets:
      AZURE_AD_CLIENT_ID:
        description: "specify client id"
        required: false
      AZURE_AD_QA_CLIENT_ID:
        description: "specify qa client id"
        required: false  
      AZURE_SUBSCRIPTION_ID:
        description: "specify sub id"
        required: true
      AZURE_AD_TENANT_ID: 
        description: "specify tenant id"
        required: true

jobs:
  code_validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{inputs.path}}
    permissions:
      id-token: write     
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: ${{ inputs.tf_version }}

      - name: Terraform Init 
        run: terraform init -backend=false
        env:
          ARM_USE_OIDC: true
    
      - name: Terraform Format
        run: terraform fmt --check
        continue-on-error: false

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: false
