name: "rw-validate"

on:
  workflow_call:
    inputs:
      path:
        description: 'Specify the path of the root Terraform module'
        required: true
        type: string

jobs:
  code_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init (No Backend)
        run: terraform init -backend=false
        working-directory: ${{ inputs.path }}
    
      - name: Terraform Format
        run: terraform fmt --check
        working-directory: ${{ inputs.path }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ inputs.path }}
