name: Run Azure Login with OIDC
on: 
 push:
   branches:
    - main
 pull_request:

   paths:
    - 'src/**'
 workflow_dispatch:

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
       shell: bash
    permissions:
      id-token: write     #permission grants the GitHub Actions workflow the capability to request an OIDC token from GitHub. This token is used for authentication with external services.
      contents: read
      
    steps:
     - name: Checkout
       uses: actions/checkout@v4
      
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2

     - name: Terraform Init
       run: terraform init
       working-directory: terraformworkspace/src
     
     - name: Terraform Format
       run: terraform fmt
       working-directory: terraformworkspace/src 

     - name: Terraform Plan
       run: terraform plan
       working-directory: terraformworkspace/src